
package services.kps.bilesikkutuk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BilesikKutukSorgulaKimlikNoServis", targetNamespace = "http://kps.nvi.gov.tr/2017/08/01", wsdlLocation = "https://kpsbasvuru.nvi.gov.tr/Services/WsdlNoPolicy.ashx?Service=BilesikKutukSorgulaKimlikNoServis&Version=2017/08/01")
public class BilesikKutukSorgulaKimlikNoServis_Service
    extends Service
{

    private final static URL BILESIKKUTUKSORGULAKIMLIKNOSERVIS_WSDL_LOCATION;
    private final static WebServiceException BILESIKKUTUKSORGULAKIMLIKNOSERVIS_EXCEPTION;
    private final static QName BILESIKKUTUKSORGULAKIMLIKNOSERVIS_QNAME = new QName("http://kps.nvi.gov.tr/2017/08/01", "BilesikKutukSorgulaKimlikNoServis");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://kpsbasvuru.nvi.gov.tr/Services/WsdlNoPolicy.ashx?Service=BilesikKutukSorgulaKimlikNoServis&Version=2017/08/01");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILESIKKUTUKSORGULAKIMLIKNOSERVIS_WSDL_LOCATION = url;
        BILESIKKUTUKSORGULAKIMLIKNOSERVIS_EXCEPTION = e;
    }

    public BilesikKutukSorgulaKimlikNoServis_Service() {
        super(__getWsdlLocation(), BILESIKKUTUKSORGULAKIMLIKNOSERVIS_QNAME);
    }

    public BilesikKutukSorgulaKimlikNoServis_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILESIKKUTUKSORGULAKIMLIKNOSERVIS_QNAME, features);
    }

    public BilesikKutukSorgulaKimlikNoServis_Service(URL wsdlLocation) {
        super(wsdlLocation, BILESIKKUTUKSORGULAKIMLIKNOSERVIS_QNAME);
    }

    public BilesikKutukSorgulaKimlikNoServis_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILESIKKUTUKSORGULAKIMLIKNOSERVIS_QNAME, features);
    }

    public BilesikKutukSorgulaKimlikNoServis_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BilesikKutukSorgulaKimlikNoServis_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BilesikKutukSorgulaKimlikNoServis
     */
    @WebEndpoint(name = "CustomBinding_BilesikKutukSorgulaKimlikNoServis")
    public BilesikKutukSorgulaKimlikNoServis getCustomBindingBilesikKutukSorgulaKimlikNoServis() {
        return super.getPort(new QName("http://kps.nvi.gov.tr/2017/08/01", "CustomBinding_BilesikKutukSorgulaKimlikNoServis"), BilesikKutukSorgulaKimlikNoServis.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BilesikKutukSorgulaKimlikNoServis
     */
    @WebEndpoint(name = "CustomBinding_BilesikKutukSorgulaKimlikNoServis")
    public BilesikKutukSorgulaKimlikNoServis getCustomBindingBilesikKutukSorgulaKimlikNoServis(WebServiceFeature... features) {
        return super.getPort(new QName("http://kps.nvi.gov.tr/2017/08/01", "CustomBinding_BilesikKutukSorgulaKimlikNoServis"), BilesikKutukSorgulaKimlikNoServis.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BILESIKKUTUKSORGULAKIMLIKNOSERVIS_EXCEPTION!= null) {
            throw BILESIKKUTUKSORGULAKIMLIKNOSERVIS_EXCEPTION;
        }
        return BILESIKKUTUKSORGULAKIMLIKNOSERVIS_WSDL_LOCATION;
    }

}
